In [4]:
import pandas as pd
import numpy as np

from MyDecisionTree import DecisionTree
from sklearn.metrics import accuracy_score, mean_absolute_error

Классификация

In [5]:
dataset = pd.DataFrame({0: [1, 0, 1, 2, 1],
                        1: [2, 5, 7, -2, 1],
                        2: [-1, 0.5, 1.5, 6, 3],
                        'target': [1, -1, 1, 1, -1]})
X = dataset.drop(columns='target').values
y = dataset['target'].values

In [49]:
np.random.seed(0)
dataset = pd.DataFrame({0: np.random.uniform(-100, 100, size=100),
                        1: np.random.uniform(-100, 100, size=100),
                        2: np.random.uniform(-100, 100, size=100),
                        'target': np.random.choice([-1, 1],size=100)})

X = dataset.drop(columns='target').values
y = dataset['target'].values

In [6]:
decision_tree = DecisionTree(max_depth=np.inf, min_samples_split=0, criterion='entropy')
fitted_tree = decision_tree.fit(X, y)

Текущая глубина: 0
Признак: 0
Значение: 0.5
Результат сравнения: True
Пришли из ветки: None
Данные:
+----+-----+-----+-----+----------+
|    |   0 |   1 |   2 |   target |
|----+-----+-----+-----+----------|
|  1 |   0 |   5 | 0.5 |       -1 |
+----+-----+-----+-----+----------+
Текущая глубина: 0
Признак: 0
Значение: 0.5
Результат сравнения: False
Пришли из ветки: None
Данные:
+----+-----+-----+------+----------+
|    |   0 |   1 |    2 |   target |
|----+-----+-----+------+----------|
|  0 |   1 |   2 | -1   |        1 |
|  2 |   1 |   7 |  1.5 |        1 |
|  3 |   2 |  -2 |  6   |        1 |
|  4 |   1 |   1 |  3   |       -1 |
+----+-----+-----+------+----------+
Текущая глубина: 1
Признак: 1
Значение: 1.5
Результат сравнения: True
Пришли из ветки: False
Данные:
+----+-----+-----+-----+----------+
|    |   0 |   1 |   2 |   target |
|----+-----+-----+-----+----------|
|  3 |   2 |  -2 |   6 |        1 |
|  4 |   1 |   1 |   3 |       -1 |
+----+-----+-----+-----+----------+
Текуща

In [7]:
y_pred = decision_tree.predict(X, fitted_tree)
y_pred

array([ 1., -1.,  1.,  1., -1.])

In [8]:
y

array([ 1, -1,  1,  1, -1], dtype=int64)

In [9]:
accuracy_score(y, y_pred)

1.0

Регрессия

In [16]:
dataset = pd.DataFrame({0: [1, 0, 1, 2, 1],
                        1: [2, 5, 7, -2, 1],
                        2: [-1, 0.5, 1.5, 6, 3],
                     'target': [6.5, 7, 10, -3.2, 1]})
X = dataset.drop(columns='target').values
y = dataset['target'].values

In [15]:
np.random.seed(0)
dataset = pd.DataFrame({0: np.random.uniform(-100, 100, size=100),
                        1: np.random.uniform(-100, 100, size=100),
                        2: np.random.uniform(-100, 100, size=100),
                        'target': np.random.uniform(-50, 50, size=100)})

X = dataset.drop(columns='target').values
y = dataset['target'].values

In [11]:
decision_tree = DecisionTree(max_depth=np.inf, min_samples_split=0, criterion='variance')
fitted_tree = decision_tree.fit(X, y)

Текущая глубина: 0
Признак: 1
Значение: 2.0
Результат сравнения: True
Пришли из ветки: None
Данные:
+----+-----+-----+-----+----------+
|    |   0 |   1 |   2 |   target |
|----+-----+-----+-----+----------|
|  3 |   2 |  -2 |   6 |     -3.2 |
|  4 |   1 |   1 |   3 |      1   |
+----+-----+-----+-----+----------+
Текущая глубина: 1
Признак: 0
Значение: 2.0
Результат сравнения: True
Пришли из ветки: True
Данные:
+----+-----+-----+-----+----------+
|    |   0 |   1 |   2 |   target |
|----+-----+-----+-----+----------|
|  4 |   1 |   1 |   3 |        1 |
+----+-----+-----+-----+----------+
Текущая глубина: 1
Признак: 0
Значение: 2.0
Результат сравнения: False
Пришли из ветки: True
Данные:
+----+-----+-----+-----+----------+
|    |   0 |   1 |   2 |   target |
|----+-----+-----+-----+----------|
|  3 |   2 |  -2 |   6 |     -3.2 |
+----+-----+-----+-----+----------+
Текущая глубина: 0
Признак: 1
Значение: 2.0
Результат сравнения: False
Пришли из ветки: None
Данные:
+----+-----+-----+----

In [12]:
y_pred = decision_tree.predict(X, fitted_tree)
y_pred

array([  6.5,   7. ,  10. ,  -3.2,   1. ])

In [13]:
y

array([  6.5,   7. ,  10. ,  -3.2,   1. ])

In [14]:
mean_absolute_error(y, y_pred)

0.0